name: build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: docker build -t dev-build .
      - name: docker push
        run: docker_push dev-build
      - name: kubectl deploy
        run: kubectl_deploy
